# Generated by Django 5.1.7 on 2025-04-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default=models.CharField(default='', max_length=150, unique=True), max_length=255, null=True),
        ),
    ]
