# Generated by Django 5.1.7 on 2025-04-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
