from django.urls import path
from . import api

urlpatterns = [
    path('', api.game_list, name='api_game_list'),
    path('manage/', api.game_list_manage, name='api_game_list_manage'),
    path('category/', api.category_list, name='api_category_list'),
    path('category/<uuid:gameId>/', api.category_game_list, name='api_category_game_list'),
    path('category/create/', api.create_category, name='api_create_category'),
    path('category/<uuid:category_id>/update/', api.update_category, name='api_update_category'),
    path('category/<uuid:category_id>/delete/', api.delete_category, name='api_delete_category'),
    path('operatingSystem/', api.operatingSystem_list, name='api_operatingSystem_list'),
    path('operatingSystem/<uuid:gameId>/', api.operatingSystem_game_list, name='api_operatingSystem_game_list'),
    path('operatingSystem/create/', api.create_operating_system, name='api_create_operating_system'),
    path('operatingSystem/<uuid:os_id>/update/', api.update_operating_system, name='api_update_operating_system'),
    path('operatingSystem/<uuid:os_id>/delete/', api.delete_operating_system, name='api_delete_operating_system'),
    path('create/', api.create_game, name='api_create_game'),
    path('create/add_category/<uuid:game_id>/<uuid:category_id>/', api.add_categories_to_game, name='api_add_categories_to_game'),
    path('create/add_operating_system/<uuid:game_id>/<uuid:operating_system_id>/', api.add_operating_systems_to_game, name='api_add_operating_systems_to_game'),
    path('<uuid:pk>/', api.game_detail, name='api_game_detail'),
    path('<uuid:game_id>/delete/', api.delete_game, name='api_delete_game'),
    path('<uuid:game_id>/update/', api.update_game, name='api_update_game'),
    path('image/<uuid:gameId>/', api.image_list, name='api_image_list'),
    path('promotion_detail/<uuid:game_id>/', api.game_promotion_detail, name='game_promotion_detail'),
    path('promotion/<uuid:game_id>/', api.game_promotion, name='game_promotion'),
    path('promotions/', api.promotion_list, name='api_promotion_list'),
    path('promotions/<uuid:promotion_id>/details/', api.promotion_details, name='api_promotion_details'),
    path('promotions/create/', api.create_promotion, name='api_create_promotion'),
    path('promotions/<uuid:promotion_id>/update/', api.update_promotion, name='api_update_promotion'),
    path('promotions/<uuid:promotion_id>/delete/', api.delete_promotion, name='api_delete_promotion'),
    path('<uuid:userId>/order/', api.user_game_list, name='api_user_game_list'),
    path('<uuid:userId>/publishergame/', api.publisher_game_list, name='api_user_game_list'),
    path('order/<uuid:game_id>/', api.order_game, name='api_game_order'),
    path('orders/', api.order_list, name='api_order_list'),
    path('orders/<uuid:order_id>/update/', api.update_order, name='api_update_order'),
    path('orders/<uuid:order_id>/delete/', api.delete_order, name='api_delete_order'),
    path('<uuid:gameId>/toggle_favorite/', api.toggle_favorite, name='api_toggle_favorite'),
    path('<uuid:game_id>/ratings/', api.game_ratings, name='api_game_ratings'),
    path('<uuid:game_id>/rate/', api.rate_game, name='api_rate_game'),
]