# Generated by Django 5.1.7 on 2025-04-03 12:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buy_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.FloatField()),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('REFUNDED', 'Refunded')], default='PAID', max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_user', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'user'), name='unique_games_user')],
            },
        ),
    ]
