# Generated by Django 5.1.7 on 2025-04-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('REFUNDED', 'Refunded'), ('WL', 'WishList')], default='PAID', max_length=10),
        ),
    ]
