# Generated by Django 5.1.7 on 2025-04-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_avg_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_description',
            field=models.TextField(null=True),
        ),
    ]
