# Generated by Django 5.1.7 on 2025-04-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_order_refund_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='approval_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('REFUNDED', 'Refunded'), ('REJECTED', 'Rejected'), ('WL', 'WishList')], default='PAID', max_length=10),
        ),
    ]
